// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.example.foreground_service_interop_plugin.ForegroundServicePlugin`
class ForegroundServicePlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ForegroundServicePlugin> $type;

  @jni$_.internal
  ForegroundServicePlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ForegroundServicePlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ForegroundServicePlugin?> nullableType =
      $ForegroundServicePlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ForegroundServicePlugin> type =
      $ForegroundServicePlugin$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ForegroundServicePlugin() {
    return ForegroundServicePlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_getService = _class.instanceMethodId(
    r'getService',
    r'()Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;',
  );

  static final _getService =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final com.example.foreground_service_interop_plugin.ExampleForegroundService getService()`
  /// The returned object must be released after use, by calling the [release] method.
  ExampleForegroundService? getService() {
    return _getService(
      reference.pointer,
      _id_getService as jni$_.JMethodIDPtr,
    ).object<ExampleForegroundService?>(
      const $ExampleForegroundService$NullableType$(),
    );
  }

  static final _id_setService = _class.instanceMethodId(
    r'setService',
    r'(Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;)V',
  );

  static final _setService =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setService(com.example.foreground_service_interop_plugin.ExampleForegroundService exampleForegroundService)`
  void setService(ExampleForegroundService? exampleForegroundService) {
    final _$exampleForegroundService =
        exampleForegroundService?.reference ?? jni$_.jNullReference;
    _setService(
      reference.pointer,
      _id_setService as jni$_.JMethodIDPtr,
      _$exampleForegroundService.pointer,
    ).check();
  }

  static final _id_isBound = _class.instanceMethodId(r'isBound', r'()Z');

  static final _isBound =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun isBound(): kotlin.Boolean`
  bool isBound() {
    return _isBound(
      reference.pointer,
      _id_isBound as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_startAndBind = _class.instanceMethodId(
    r'startAndBind',
    r'(Landroid/content/Context;)V',
  );

  static final _startAndBind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun startAndBind(context: android.content.Context): kotlin.Unit`
  void startAndBind(jni$_.JObject context) {
    final _$context = context.reference;
    _startAndBind(
      reference.pointer,
      _id_startAndBind as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_unbind = _class.instanceMethodId(
    r'unbind',
    r'(Landroid/content/Context;)V',
  );

  static final _unbind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun unbind(context: android.content.Context): kotlin.Unit`
  void unbind(jni$_.JObject context) {
    final _$context = context.reference;
    _unbind(
      reference.pointer,
      _id_unbind as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_stopAndUnbind = _class.instanceMethodId(
    r'stopAndUnbind',
    r'(Landroid/content/Context;)V',
  );

  static final _stopAndUnbind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun stopAndUnbind(context: android.content.Context): kotlin.Unit`
  void stopAndUnbind(jni$_.JObject context) {
    final _$context = context.reference;
    _stopAndUnbind(
      reference.pointer,
      _id_stopAndUnbind as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_sendMessage = _class.instanceMethodId(
    r'sendMessage',
    r'(Ljava/lang/String;)V',
  );

  static final _sendMessage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun sendMessage(message: kotlin.String): kotlin.Unit`
  void sendMessage(jni$_.JString string) {
    final _$string = string.reference;
    _sendMessage(
      reference.pointer,
      _id_sendMessage as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_setOnReplyListener = _class.instanceMethodId(
    r'setOnReplyListener',
    r'(Lcom/example/foreground_service_interop_plugin/ReplyListenerProxy$OnReplyListener;)V',
  );

  static final _setOnReplyListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setOnReplyListener(listener: com.example.foreground_service_interop_plugin.ReplyListenerProxy.OnReplyListener): kotlin.Unit`
  void setOnReplyListener(ReplyListenerProxy$OnReplyListener onReplyListener) {
    final _$onReplyListener = onReplyListener.reference;
    _setOnReplyListener(
      reference.pointer,
      _id_setOnReplyListener as jni$_.JMethodIDPtr,
      _$onReplyListener.pointer,
    ).check();
  }

  static final _id_hasPostNotificationsPermission = _class.instanceMethodId(
    r'hasPostNotificationsPermission',
    r'(Landroid/content/Context;)Z',
  );

  static final _hasPostNotificationsPermission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun hasPostNotificationsPermission(context: android.content.Context): kotlin.Boolean`
  bool hasPostNotificationsPermission(jni$_.JObject context) {
    final _$context = context.reference;
    return _hasPostNotificationsPermission(
      reference.pointer,
      _id_hasPostNotificationsPermission as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).boolean;
  }

  static final _id_requestPostNotificationsPermission = _class.instanceMethodId(
    r'requestPostNotificationsPermission',
    r'(Landroid/app/Activity;I)V',
  );

  static final _requestPostNotificationsPermission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun requestPostNotificationsPermission(activity: android.app.Activity, requestCode: kotlin.Int): kotlin.Unit`
  void requestPostNotificationsPermission(jni$_.JObject activity, int i) {
    final _$activity = activity.reference;
    _requestPostNotificationsPermission(
      reference.pointer,
      _id_requestPostNotificationsPermission as jni$_.JMethodIDPtr,
      _$activity.pointer,
      i,
    ).check();
  }
}

final class $ForegroundServicePlugin$NullableType$
    extends jni$_.JType<ForegroundServicePlugin?> {
  @jni$_.internal
  const $ForegroundServicePlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ForegroundServicePlugin;';

  @jni$_.internal
  @core$_.override
  ForegroundServicePlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : ForegroundServicePlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ForegroundServicePlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ForegroundServicePlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ForegroundServicePlugin$NullableType$) &&
        other is $ForegroundServicePlugin$NullableType$;
  }
}

final class $ForegroundServicePlugin$Type$
    extends jni$_.JType<ForegroundServicePlugin> {
  @jni$_.internal
  const $ForegroundServicePlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ForegroundServicePlugin;';

  @jni$_.internal
  @core$_.override
  ForegroundServicePlugin fromReference(jni$_.JReference reference) =>
      ForegroundServicePlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ForegroundServicePlugin?> get nullableType =>
      const $ForegroundServicePlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ForegroundServicePlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ForegroundServicePlugin$Type$) &&
        other is $ForegroundServicePlugin$Type$;
  }
}

/// from: `com.example.foreground_service_interop_plugin.ExampleForegroundService$Companion`
class ExampleForegroundService$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ExampleForegroundService$Companion> $type;

  @jni$_.internal
  ExampleForegroundService$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ExampleForegroundService$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService$Companion?> nullableType =
      $ExampleForegroundService$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService$Companion> type =
      $ExampleForegroundService$Companion$Type$();
  static final _id_start = _class.instanceMethodId(
    r'start',
    r'(Landroid/content/Context;Ljava/lang/String;)V',
  );

  static final _start =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun start(context: android.content.Context, message: kotlin.String): kotlin.Unit`
  void start(jni$_.JObject context, jni$_.JString string) {
    final _$context = context.reference;
    final _$string = string.reference;
    _start(
      reference.pointer,
      _id_start as jni$_.JMethodIDPtr,
      _$context.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_enqueueReply = _class.instanceMethodId(
    r'enqueueReply',
    r'(Landroid/content/Context;Ljava/lang/String;)V',
  );

  static final _enqueueReply =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun enqueueReply(context: android.content.Context, replyText: kotlin.String): kotlin.Unit`
  void enqueueReply(jni$_.JObject context, jni$_.JString string) {
    final _$context = context.reference;
    final _$string = string.reference;
    _enqueueReply(
      reference.pointer,
      _id_enqueueReply as jni$_.JMethodIDPtr,
      _$context.pointer,
      _$string.pointer,
    ).check();
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ExampleForegroundService$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return ExampleForegroundService$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $ExampleForegroundService$Companion$NullableType$
    extends jni$_.JType<ExampleForegroundService$Companion?> {
  @jni$_.internal
  const $ExampleForegroundService$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService$Companion;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService$Companion? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : ExampleForegroundService$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($ExampleForegroundService$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($ExampleForegroundService$Companion$NullableType$) &&
        other is $ExampleForegroundService$Companion$NullableType$;
  }
}

final class $ExampleForegroundService$Companion$Type$
    extends jni$_.JType<ExampleForegroundService$Companion> {
  @jni$_.internal
  const $ExampleForegroundService$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService$Companion;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService$Companion fromReference(
    jni$_.JReference reference,
  ) => ExampleForegroundService$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService$Companion?> get nullableType =>
      const $ExampleForegroundService$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ExampleForegroundService$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ExampleForegroundService$Companion$Type$) &&
        other is $ExampleForegroundService$Companion$Type$;
  }
}

/// from: `com.example.foreground_service_interop_plugin.ExampleForegroundService$LocalBinder`
class ExampleForegroundService$LocalBinder extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ExampleForegroundService$LocalBinder> $type;

  @jni$_.internal
  ExampleForegroundService$LocalBinder.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ExampleForegroundService$LocalBinder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService$LocalBinder?> nullableType =
      $ExampleForegroundService$LocalBinder$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService$LocalBinder> type =
      $ExampleForegroundService$LocalBinder$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.example.foreground_service_interop_plugin.ExampleForegroundService $outerClass)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ExampleForegroundService$LocalBinder(
    ExampleForegroundService $outerClass,
  ) {
    final _$$outerClass = $outerClass.reference;
    return ExampleForegroundService$LocalBinder.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$$outerClass.pointer,
      ).reference,
    );
  }

  static final _id_getService = _class.instanceMethodId(
    r'getService',
    r'()Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;',
  );

  static final _getService =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun getService(): com.example.foreground_service_interop_plugin.ExampleForegroundService`
  /// The returned object must be released after use, by calling the [release] method.
  ExampleForegroundService getService() {
    return _getService(
      reference.pointer,
      _id_getService as jni$_.JMethodIDPtr,
    ).object<ExampleForegroundService>(const $ExampleForegroundService$Type$());
  }
}

final class $ExampleForegroundService$LocalBinder$NullableType$
    extends jni$_.JType<ExampleForegroundService$LocalBinder?> {
  @jni$_.internal
  const $ExampleForegroundService$LocalBinder$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService$LocalBinder;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService$LocalBinder? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : ExampleForegroundService$LocalBinder.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService$LocalBinder?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($ExampleForegroundService$LocalBinder$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($ExampleForegroundService$LocalBinder$NullableType$) &&
        other is $ExampleForegroundService$LocalBinder$NullableType$;
  }
}

final class $ExampleForegroundService$LocalBinder$Type$
    extends jni$_.JType<ExampleForegroundService$LocalBinder> {
  @jni$_.internal
  const $ExampleForegroundService$LocalBinder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService$LocalBinder;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService$LocalBinder fromReference(
    jni$_.JReference reference,
  ) => ExampleForegroundService$LocalBinder.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService$LocalBinder?> get nullableType =>
      const $ExampleForegroundService$LocalBinder$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ExampleForegroundService$LocalBinder$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ExampleForegroundService$LocalBinder$Type$) &&
        other is $ExampleForegroundService$LocalBinder$Type$;
  }
}

/// from: `com.example.foreground_service_interop_plugin.ExampleForegroundService`
class ExampleForegroundService extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ExampleForegroundService> $type;

  @jni$_.internal
  ExampleForegroundService.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ExampleForegroundService',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService?> nullableType =
      $ExampleForegroundService$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ExampleForegroundService> type =
      $ExampleForegroundService$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService$Companion;',
  );

  /// from: `static public final com.example.foreground_service_interop_plugin.ExampleForegroundService$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static ExampleForegroundService$Companion get Companion => _id_Companion.get(
    _class,
    const $ExampleForegroundService$Companion$Type$(),
  );

  static final _id_CHANNEL_ID = _class.staticFieldId(
    r'CHANNEL_ID',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String CHANNEL_ID`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get CHANNEL_ID =>
      _id_CHANNEL_ID.get(_class, const jni$_.$JString$Type$());

  /// from: `static public final int NOTIFICATION_ID`
  static const NOTIFICATION_ID = 1001;
  static final _id_ACTION_POST_MESSAGE = _class.staticFieldId(
    r'ACTION_POST_MESSAGE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ACTION_POST_MESSAGE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get ACTION_POST_MESSAGE =>
      _id_ACTION_POST_MESSAGE.get(_class, const jni$_.$JString$Type$());

  static final _id_ACTION_HANDLE_REPLY = _class.staticFieldId(
    r'ACTION_HANDLE_REPLY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ACTION_HANDLE_REPLY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get ACTION_HANDLE_REPLY =>
      _id_ACTION_HANDLE_REPLY.get(_class, const jni$_.$JString$Type$());

  static final _id_ACTION_REPLY = _class.staticFieldId(
    r'ACTION_REPLY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ACTION_REPLY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get ACTION_REPLY =>
      _id_ACTION_REPLY.get(_class, const jni$_.$JString$Type$());

  static final _id_EXTRA_MESSAGE = _class.staticFieldId(
    r'EXTRA_MESSAGE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String EXTRA_MESSAGE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get EXTRA_MESSAGE =>
      _id_EXTRA_MESSAGE.get(_class, const jni$_.$JString$Type$());

  static final _id_EXTRA_REPLY_TEXT = _class.staticFieldId(
    r'EXTRA_REPLY_TEXT',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String EXTRA_REPLY_TEXT`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get EXTRA_REPLY_TEXT =>
      _id_EXTRA_REPLY_TEXT.get(_class, const jni$_.$JString$Type$());

  static final _id_KEY_TEXT_REPLY = _class.staticFieldId(
    r'KEY_TEXT_REPLY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String KEY_TEXT_REPLY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get KEY_TEXT_REPLY =>
      _id_KEY_TEXT_REPLY.get(_class, const jni$_.$JString$Type$());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ExampleForegroundService() {
    return ExampleForegroundService.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_onCreate = _class.instanceMethodId(r'onCreate', r'()V');

  static final _onCreate =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onCreate(): kotlin.Unit`
  void onCreate() {
    _onCreate(reference.pointer, _id_onCreate as jni$_.JMethodIDPtr).check();
  }

  static final _id_onBind = _class.instanceMethodId(
    r'onBind',
    r'(Landroid/content/Intent;)Landroid/os/IBinder;',
  );

  static final _onBind =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onBind(intent: android.content.Intent): android.os.IBinder`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject onBind(jni$_.JObject intent) {
    final _$intent = intent.reference;
    return _onBind(
      reference.pointer,
      _id_onBind as jni$_.JMethodIDPtr,
      _$intent.pointer,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_onStartCommand = _class.instanceMethodId(
    r'onStartCommand',
    r'(Landroid/content/Intent;II)I',
  );

  static final _onStartCommand =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
            )
          >();

  /// from: `public fun onStartCommand(intent: android.content.Intent?, flags: kotlin.Int, startId: kotlin.Int): kotlin.Int`
  int onStartCommand(jni$_.JObject? intent, int i, int i1) {
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    return _onStartCommand(
      reference.pointer,
      _id_onStartCommand as jni$_.JMethodIDPtr,
      _$intent.pointer,
      i,
      i1,
    ).integer;
  }

  static final _id_receiveMessage = _class.instanceMethodId(
    r'receiveMessage',
    r'(Ljava/lang/String;)V',
  );

  static final _receiveMessage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun receiveMessage(message: kotlin.String): kotlin.Unit`
  void receiveMessage(jni$_.JString string) {
    final _$string = string.reference;
    _receiveMessage(
      reference.pointer,
      _id_receiveMessage as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_setOnReplyListener = _class.instanceMethodId(
    r'setOnReplyListener',
    r'(Lkotlin/jvm/functions/Function1;)V',
  );

  static final _setOnReplyListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setOnReplyListener(listener: kotlin.Function1<kotlin.String, kotlin.Unit>): kotlin.Unit`
  void setOnReplyListener(jni$_.JObject function1) {
    final _$function1 = function1.reference;
    _setOnReplyListener(
      reference.pointer,
      _id_setOnReplyListener as jni$_.JMethodIDPtr,
      _$function1.pointer,
    ).check();
  }
}

final class $ExampleForegroundService$NullableType$
    extends jni$_.JType<ExampleForegroundService?> {
  @jni$_.internal
  const $ExampleForegroundService$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : ExampleForegroundService.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ExampleForegroundService$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ExampleForegroundService$NullableType$) &&
        other is $ExampleForegroundService$NullableType$;
  }
}

final class $ExampleForegroundService$Type$
    extends jni$_.JType<ExampleForegroundService> {
  @jni$_.internal
  const $ExampleForegroundService$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ExampleForegroundService;';

  @jni$_.internal
  @core$_.override
  ExampleForegroundService fromReference(jni$_.JReference reference) =>
      ExampleForegroundService.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ExampleForegroundService?> get nullableType =>
      const $ExampleForegroundService$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ExampleForegroundService$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ExampleForegroundService$Type$) &&
        other is $ExampleForegroundService$Type$;
  }
}

/// from: `com.example.foreground_service_interop_plugin.ReplyListenerProxy$OnReplyListener`
class ReplyListenerProxy$OnReplyListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ReplyListenerProxy$OnReplyListener> $type;

  @jni$_.internal
  ReplyListenerProxy$OnReplyListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ReplyListenerProxy$OnReplyListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ReplyListenerProxy$OnReplyListener?> nullableType =
      $ReplyListenerProxy$OnReplyListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ReplyListenerProxy$OnReplyListener> type =
      $ReplyListenerProxy$OnReplyListener$Type$();
  static final _id_onReply = _class.instanceMethodId(
    r'onReply',
    r'(Ljava/lang/String;)V',
  );

  static final _onReply =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onReply(replyText: kotlin.String): kotlin.Unit`
  void onReply(jni$_.JString string) {
    final _$string = string.reference;
    _onReply(
      reference.pointer,
      _id_onReply as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_onDisconnected = _class.instanceMethodId(
    r'onDisconnected',
    r'()V',
  );

  static final _onDisconnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onDisconnected(): kotlin.Unit`
  void onDisconnected() {
    _onDisconnected(
      reference.pointer,
      _id_onDisconnected as jni$_.JMethodIDPtr,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $ReplyListenerProxy$OnReplyListener> _$impls =
      {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onReply(Ljava/lang/String;)V') {
        _$impls[$p]!.onReply(
          $a![0]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onDisconnected()V') {
        _$impls[$p]!.onDisconnected();
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $ReplyListenerProxy$OnReplyListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.example.foreground_service_interop_plugin.ReplyListenerProxy$OnReplyListener',
      $p,
      _$invokePointer,
      [
        if ($impl.onReply$async) r'onReply(Ljava/lang/String;)V',
        if ($impl.onDisconnected$async) r'onDisconnected()V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory ReplyListenerProxy$OnReplyListener.implement(
    $ReplyListenerProxy$OnReplyListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return ReplyListenerProxy$OnReplyListener.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $ReplyListenerProxy$OnReplyListener {
  factory $ReplyListenerProxy$OnReplyListener({
    required void Function(jni$_.JString string) onReply,
    bool onReply$async,
    required void Function() onDisconnected,
    bool onDisconnected$async,
  }) = _$ReplyListenerProxy$OnReplyListener;

  void onReply(jni$_.JString string);
  bool get onReply$async => false;
  void onDisconnected();
  bool get onDisconnected$async => false;
}

final class _$ReplyListenerProxy$OnReplyListener
    with $ReplyListenerProxy$OnReplyListener {
  _$ReplyListenerProxy$OnReplyListener({
    required void Function(jni$_.JString string) onReply,
    this.onReply$async = false,
    required void Function() onDisconnected,
    this.onDisconnected$async = false,
  }) : _onReply = onReply,
       _onDisconnected = onDisconnected;

  final void Function(jni$_.JString string) _onReply;
  final bool onReply$async;
  final void Function() _onDisconnected;
  final bool onDisconnected$async;

  void onReply(jni$_.JString string) {
    return _onReply(string);
  }

  void onDisconnected() {
    return _onDisconnected();
  }
}

final class $ReplyListenerProxy$OnReplyListener$NullableType$
    extends jni$_.JType<ReplyListenerProxy$OnReplyListener?> {
  @jni$_.internal
  const $ReplyListenerProxy$OnReplyListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ReplyListenerProxy$OnReplyListener;';

  @jni$_.internal
  @core$_.override
  ReplyListenerProxy$OnReplyListener? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : ReplyListenerProxy$OnReplyListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ReplyListenerProxy$OnReplyListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($ReplyListenerProxy$OnReplyListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($ReplyListenerProxy$OnReplyListener$NullableType$) &&
        other is $ReplyListenerProxy$OnReplyListener$NullableType$;
  }
}

final class $ReplyListenerProxy$OnReplyListener$Type$
    extends jni$_.JType<ReplyListenerProxy$OnReplyListener> {
  @jni$_.internal
  const $ReplyListenerProxy$OnReplyListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ReplyListenerProxy$OnReplyListener;';

  @jni$_.internal
  @core$_.override
  ReplyListenerProxy$OnReplyListener fromReference(
    jni$_.JReference reference,
  ) => ReplyListenerProxy$OnReplyListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ReplyListenerProxy$OnReplyListener?> get nullableType =>
      const $ReplyListenerProxy$OnReplyListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ReplyListenerProxy$OnReplyListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ReplyListenerProxy$OnReplyListener$Type$) &&
        other is $ReplyListenerProxy$OnReplyListener$Type$;
  }
}

/// from: `com.example.foreground_service_interop_plugin.ReplyListenerProxy`
class ReplyListenerProxy extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ReplyListenerProxy> $type;

  @jni$_.internal
  ReplyListenerProxy.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/foreground_service_interop_plugin/ReplyListenerProxy',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ReplyListenerProxy?> nullableType =
      $ReplyListenerProxy$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ReplyListenerProxy> type =
      $ReplyListenerProxy$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ReplyListenerProxy() {
    return ReplyListenerProxy.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $ReplyListenerProxy$NullableType$
    extends jni$_.JType<ReplyListenerProxy?> {
  @jni$_.internal
  const $ReplyListenerProxy$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ReplyListenerProxy;';

  @jni$_.internal
  @core$_.override
  ReplyListenerProxy? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : ReplyListenerProxy.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ReplyListenerProxy?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ReplyListenerProxy$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ReplyListenerProxy$NullableType$) &&
        other is $ReplyListenerProxy$NullableType$;
  }
}

final class $ReplyListenerProxy$Type$ extends jni$_.JType<ReplyListenerProxy> {
  @jni$_.internal
  const $ReplyListenerProxy$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/foreground_service_interop_plugin/ReplyListenerProxy;';

  @jni$_.internal
  @core$_.override
  ReplyListenerProxy fromReference(jni$_.JReference reference) =>
      ReplyListenerProxy.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ReplyListenerProxy?> get nullableType =>
      const $ReplyListenerProxy$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ReplyListenerProxy$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ReplyListenerProxy$Type$) &&
        other is $ReplyListenerProxy$Type$;
  }
}

/// from: `android.content.ServiceConnection`
class ServiceConnection extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ServiceConnection> $type;

  @jni$_.internal
  ServiceConnection.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/content/ServiceConnection',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ServiceConnection?> nullableType =
      $ServiceConnection$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ServiceConnection> type = $ServiceConnection$Type$();
  static final _id_onBindingDied = _class.instanceMethodId(
    r'onBindingDied',
    r'(Landroid/content/ComponentName;)V',
  );

  static final _onBindingDied =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onBindingDied(android.content.ComponentName componentName)`
  void onBindingDied(jni$_.JObject? componentName) {
    final _$componentName = componentName?.reference ?? jni$_.jNullReference;
    _onBindingDied(
      reference.pointer,
      _id_onBindingDied as jni$_.JMethodIDPtr,
      _$componentName.pointer,
    ).check();
  }

  static final _id_onNullBinding = _class.instanceMethodId(
    r'onNullBinding',
    r'(Landroid/content/ComponentName;)V',
  );

  static final _onNullBinding =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onNullBinding(android.content.ComponentName componentName)`
  void onNullBinding(jni$_.JObject? componentName) {
    final _$componentName = componentName?.reference ?? jni$_.jNullReference;
    _onNullBinding(
      reference.pointer,
      _id_onNullBinding as jni$_.JMethodIDPtr,
      _$componentName.pointer,
    ).check();
  }

  static final _id_onServiceConnected = _class.instanceMethodId(
    r'onServiceConnected',
    r'(Landroid/content/ComponentName;Landroid/os/IBinder;)V',
  );

  static final _onServiceConnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onServiceConnected(android.content.ComponentName componentName, android.os.IBinder iBinder)`
  void onServiceConnected(
    jni$_.JObject? componentName,
    jni$_.JObject? iBinder,
  ) {
    final _$componentName = componentName?.reference ?? jni$_.jNullReference;
    final _$iBinder = iBinder?.reference ?? jni$_.jNullReference;
    _onServiceConnected(
      reference.pointer,
      _id_onServiceConnected as jni$_.JMethodIDPtr,
      _$componentName.pointer,
      _$iBinder.pointer,
    ).check();
  }

  static final _id_onServiceDisconnected = _class.instanceMethodId(
    r'onServiceDisconnected',
    r'(Landroid/content/ComponentName;)V',
  );

  static final _onServiceDisconnected =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onServiceDisconnected(android.content.ComponentName componentName)`
  void onServiceDisconnected(jni$_.JObject? componentName) {
    final _$componentName = componentName?.reference ?? jni$_.jNullReference;
    _onServiceDisconnected(
      reference.pointer,
      _id_onServiceDisconnected as jni$_.JMethodIDPtr,
      _$componentName.pointer,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $ServiceConnection> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onBindingDied(Landroid/content/ComponentName;)V') {
        _$impls[$p]!.onBindingDied(
          $a![0]?.as(const jni$_.$JObject$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onNullBinding(Landroid/content/ComponentName;)V') {
        _$impls[$p]!.onNullBinding(
          $a![0]?.as(const jni$_.$JObject$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d ==
          r'onServiceConnected(Landroid/content/ComponentName;Landroid/os/IBinder;)V') {
        _$impls[$p]!.onServiceConnected(
          $a![0]?.as(const jni$_.$JObject$Type$(), releaseOriginal: true),
          $a![1]?.as(const jni$_.$JObject$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onServiceDisconnected(Landroid/content/ComponentName;)V') {
        _$impls[$p]!.onServiceDisconnected(
          $a![0]?.as(const jni$_.$JObject$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $ServiceConnection $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'android.content.ServiceConnection', $p, _$invokePointer, [
      if ($impl.onBindingDied$async)
        r'onBindingDied(Landroid/content/ComponentName;)V',
      if ($impl.onNullBinding$async)
        r'onNullBinding(Landroid/content/ComponentName;)V',
      if ($impl.onServiceConnected$async)
        r'onServiceConnected(Landroid/content/ComponentName;Landroid/os/IBinder;)V',
      if ($impl.onServiceDisconnected$async)
        r'onServiceDisconnected(Landroid/content/ComponentName;)V',
    ]);
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory ServiceConnection.implement($ServiceConnection $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return ServiceConnection.fromReference($i.implementReference());
  }
}

abstract base mixin class $ServiceConnection {
  factory $ServiceConnection({
    required void Function(jni$_.JObject? componentName) onBindingDied,
    bool onBindingDied$async,
    required void Function(jni$_.JObject? componentName) onNullBinding,
    bool onNullBinding$async,
    required void Function(jni$_.JObject? componentName, jni$_.JObject? iBinder)
    onServiceConnected,
    bool onServiceConnected$async,
    required void Function(jni$_.JObject? componentName) onServiceDisconnected,
    bool onServiceDisconnected$async,
  }) = _$ServiceConnection;

  void onBindingDied(jni$_.JObject? componentName);
  bool get onBindingDied$async => false;
  void onNullBinding(jni$_.JObject? componentName);
  bool get onNullBinding$async => false;
  void onServiceConnected(jni$_.JObject? componentName, jni$_.JObject? iBinder);
  bool get onServiceConnected$async => false;
  void onServiceDisconnected(jni$_.JObject? componentName);
  bool get onServiceDisconnected$async => false;
}

final class _$ServiceConnection with $ServiceConnection {
  _$ServiceConnection({
    required void Function(jni$_.JObject? componentName) onBindingDied,
    this.onBindingDied$async = false,
    required void Function(jni$_.JObject? componentName) onNullBinding,
    this.onNullBinding$async = false,
    required void Function(jni$_.JObject? componentName, jni$_.JObject? iBinder)
    onServiceConnected,
    this.onServiceConnected$async = false,
    required void Function(jni$_.JObject? componentName) onServiceDisconnected,
    this.onServiceDisconnected$async = false,
  }) : _onBindingDied = onBindingDied,
       _onNullBinding = onNullBinding,
       _onServiceConnected = onServiceConnected,
       _onServiceDisconnected = onServiceDisconnected;

  final void Function(jni$_.JObject? componentName) _onBindingDied;
  final bool onBindingDied$async;
  final void Function(jni$_.JObject? componentName) _onNullBinding;
  final bool onNullBinding$async;
  final void Function(jni$_.JObject? componentName, jni$_.JObject? iBinder)
  _onServiceConnected;
  final bool onServiceConnected$async;
  final void Function(jni$_.JObject? componentName) _onServiceDisconnected;
  final bool onServiceDisconnected$async;

  void onBindingDied(jni$_.JObject? componentName) {
    return _onBindingDied(componentName);
  }

  void onNullBinding(jni$_.JObject? componentName) {
    return _onNullBinding(componentName);
  }

  void onServiceConnected(
    jni$_.JObject? componentName,
    jni$_.JObject? iBinder,
  ) {
    return _onServiceConnected(componentName, iBinder);
  }

  void onServiceDisconnected(jni$_.JObject? componentName) {
    return _onServiceDisconnected(componentName);
  }
}

final class $ServiceConnection$NullableType$
    extends jni$_.JType<ServiceConnection?> {
  @jni$_.internal
  const $ServiceConnection$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/ServiceConnection;';

  @jni$_.internal
  @core$_.override
  ServiceConnection? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : ServiceConnection.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ServiceConnection?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ServiceConnection$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ServiceConnection$NullableType$) &&
        other is $ServiceConnection$NullableType$;
  }
}

final class $ServiceConnection$Type$ extends jni$_.JType<ServiceConnection> {
  @jni$_.internal
  const $ServiceConnection$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/ServiceConnection;';

  @jni$_.internal
  @core$_.override
  ServiceConnection fromReference(jni$_.JReference reference) =>
      ServiceConnection.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ServiceConnection?> get nullableType =>
      const $ServiceConnection$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ServiceConnection$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ServiceConnection$Type$) &&
        other is $ServiceConnection$Type$;
  }
}
