name: android_intent_example
description: "Demonstrates how to use the android_intent plugin."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  android_intent:
    path: ../

  cupertino_icons: ^1.0.8
  jni: ^0.14.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
