name: android_intent
description: "Plugin to send Android Intents from Flutter"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^1.0.0
  jni_flutter: ^1.0.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jnigen: ^0.16.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: com.example.android_intent
        pluginClass: ActivityResultListenerProxy
