name: pdf
description: "A new Flutter FFI plugin project to view PDFs."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  jni: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.13.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: com.example.pdf
        pluginClass: PDFViewFlutterPlugin
      # ios:
      #   ffiPlugin: true
