name: uikit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  # objective_c: ^8.1.0
  objective_c: ^9.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # ffigen: ^19.1.0
  ffigen: ^20.0.0-dev.0

flutter:
  uses-material-design: true

ffigen:
  name: UIKit
  description: Bindings for UIKit for iOS.
  language: objc
  output: "lib/uikit_bindings.g.dart"
  headers:
    entry-points:
      - "Headers/NSToolbar+UIKitAdditions.h"
      - "Headers/UIAlertController.h"
      - "Headers/UIApplication.h"
      - "Headers/UIBarButtonItem.h"
      - "Headers/UIBarButtonItemAppearance.h"
      - "Headers/UIBarButtonItemGroup.h"
      - "Headers/UIColor.h"
      - "Headers/UICommand.h"
      - "Headers/UIFont.h"
      - "Headers/UIGeometry.h"
      - "Headers/UIInterface.h"
      - "Headers/UIKitDefines.h"
      - "Headers/UILabel.h"
      - "Headers/UIMenu.h"
      - "Headers/UINavigationController.h"
      - "Headers/UINavigationItem.h"
      - "Headers/UIScrollView.h"
      - "Headers/UISpringLoadedInteractionSupporting.h"
      - "Headers/UISwitch.h"
      # - "Headers/UIResponder.h"
      # - "Headers/UIView.h"
      - "Headers/UIViewController.h"
      - "Headers/UIWindow.h"
  include-transitive-objc-interfaces: false
  include-transitive-objc-protocols: false
  exclude-all-by-default: true
 
  objc-protocols:
    member-filter:
      UI.*:  # Matches all protocols starting with UI.
        exclude:
          - initWithFrame.*  # Remove all initWithFrame methods from these protocols.
    # exclude:
    #   - "NSAnimatablePropertyContainer"
    #   - "_UIKit_NSAnimatablePropertyContainer"
  objc-interfaces:
    # member-filter:
    #   MyInterface:
    #     include:
    #       - "someMethod:withArg:"
    #     # Since MyInterface has an include rule, all other methods
    #     # are excluded by default.
    exclude:
      - "UIResponder"
      # - "UIWindow"
    include:
      - "UIAlertAction"
      - "UIAlertController"
      - "UIApplication"
      - "UIBarButtonItem"
      - "UIBarButtonItemAppearance"
      - "UIBarButtonItemGroup"
      - "UIBarButtonItemStyle"
      - "UIBarButtonSystemItem"
      - "UIColor"
      - "UIFont"
      - "UIImage"
      - "UILabel"
      - "UIMenu"
      - "UINavigationBarAppearance"
      - "UINavigationController"
      - "UINavigationItem"
      - "UIScrollView"
      - "UISearchTextField"
      - "UISwitch"
      - "UITitlebar"
      - "UIViewController"
      - "UIWindow"

