name: pdf_viewer
description: "An example Flutter project to showcase plugin with jnigen and ffigen"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

workspace:
  - packages/pdf

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
